-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.


SELECT  D.HISTORY_ID
        , ROUND(IF(D.DISCOUNT_RATE IS NULL, D.DAILY_FEE * D.DATE_DIFF, D.DAILY_FEE * D.DATE_DIFF * (100-D.DISCOUNT_RATE)*0.01),0) AS FEE
FROM (
        SELECT A.*, B.HISTORY_ID, DATEDIFF(B.END_DATE, B.START_DATE) + 1 AS DATE_DIFF, C.DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_CAR A
        LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
           ON A.CAR_ID = B.CAR_ID
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
           ON CASE WHEN DATEDIFF(B.END_DATE, B.START_DATE) BETWEEN 7 AND 29 THEN C.PLAN_ID = 10
           WHEN DATEDIFF(B.END_DATE, B.START_DATE) BETWEEN 30 AND 89 THEN C.PLAN_ID = 11
           WHEN DATEDIFF(B.END_DATE, B.START_DATE) >= 90 THEN C.PLAN_ID = 12 END
        WHERE A.CAR_TYPE = '트럭'
    ) AS D
ORDER
    BY FEE DESC 
         , HISTORY_ID DESC;